### ISSUE TITLE
New Wordfence  CLI install produces "Latin-1" UnicodeEncodeError

### ISSUE THREAD

**Issue by cwgrote** [wordfence/wordfence-cli#232] opened 2024-01-26 14:49 UTC
I installed Wordfence CLI on Ubuntu 22.04 server using the downloaded .deb version. When I enter “sudo wordfence configure” from the command line I get “Error: ‘latin-1’ codec can’t encode characters in position 13-15: ordinal not in range(256)”.  Please advise how to proceed. Thanks! Here is the output using "--debug":

sudo wordfence configure --debug
                             
Traceback (most recent call last):
  File "/usr/bin/wordfence", line 8, in <module>  sys.exit(main())
  File "/usr/lib/python3/dist-packages/wordfence/cli/cli.py", line 173, in main return 
        exception_handler.process_exception(exception)
  File "/usr/lib/python3/dist-packages/wordfence/cli/cli.py", line 43, in process_exception  raise exception
  File "/usr/lib/python3/dist-packages/wordfence/cli/cli.py", line 171, in main return cli.invoke()
  File "/usr/lib/python3/dist-packages/wordfence/cli/cli.py", line 117, in invoke show_welcome_banner_if_enabled(self.config)
  File "/usr/lib/python3/dist-packages/wordfence/cli/banner/banner.py", line 116, in show_welcome_banner_if_enabled
    show_welcome_banner()
  File "/usr/lib/python3/dist-packages/wordfence/cli/banner/banner.py", line 105, in show_welcome_banner banner.display()
  File "/usr/lib/python3/dist-packages/wordfence/cli/banner/banner.py", line 75, in display print(row)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 13-15: ordinal not in range(256)

**Comment by akenion** [comment] 2024-01-26 15:35
It looks like the encoding of your terminal is `latin-1` while Wordfence CLI is expecting `utf-8`. This should only be problematic when displaying the banner, so attempting to run the same command with `--no-banner` should allow working around this issue in the meantime. Alternatively, if it's possible to set your terminal to use `utf-8` instead that should also resolve it.

This does need to be addressed internally in Wordfence CLI to allow gracefully handling encodings other than `utf-8`. We should be able to address this in the next release, but I can't provide an exact timeline at this point.

**Comment by cwgrote** [comment] 2024-01-26 21:49
Thanks you very much for the reply. It was very helpful. In researching the encoding error I ran across a suggestion to enter "locale-gen en_US.utf8" which I did, but it did not fix the encoding error. Running wordfence with --no-banner got me going so I could read the help information and run a successful scan. The return from --version is "Wordfence CLI 3.0.1 "Ghost Rider" PCRE Version: 8.39 2016-06-14 - JIT Supported: Yes". I am wondering if there is a way to get the newest version of the free signature set. I have a small web site with only five non-paying domains and the commercial license  cost is too prohibitive for me. Thanks again for getting me going with the CLI version.

**Comment by akenion** [comment] 2024-01-29 16:08
`locale-gen en_US.utf-8` should generate the locale files, but does not actually change the current locale. I believe you need to run `update-locale LANG=en_US.utf-8` to actually change the locale, though other environment variables may need to be set as well.

Wordfence CLI automatically fetches the newest version of the free signature set as needed, caching it for 24 hours. If you need to force an update of the signature set you can use the `--purge-cache` option, but this is generally not necessary and will only slow down scans if used regularly. The commercial signature set is only available with a paid license.

**Comment by cwgrote** [comment] 2024-01-30 14:18
Thanks again for your reply.  I thought the "PCRE Version: 8.39 2016-06-1" indicated a very old signature file and I needed to download the newest version from somewhere. If I pay for the commercial signature set I am only allowed to run the Wordfence CLI with that set on one of my five virtual domains, correct?

**Comment by akenion** [comment] 2024-01-30 15:12
`PCRE Version: 8.39 2016-06-1` indicates the installed version of the PCRE library which Wordfence CLI uses to evaluate signature patterns. This version is generally controlled by the operating system and the old date here is no cause for concern. This doesn't indicate the version of the actual malware signatures in use. Those will never be older than 24 hours.

Regarding the commercial signature set, at present, the base license tier allows scanning up to 100 sites, so you should only need a single license to scan all five of your sites.

**Comment by cwgrote** [comment] 2024-01-30 16:10
That is good news. So is the commercial Wordfence CLI license different than the plugin Wordfence Premium license? I am very happy with the CLI version and want to make sure I am able to get the commercial signature set for the CLI version. Thank you for your quick responses.  I have had a lot of trouble cleaning my hacked websites, and I think I have it narrowed down to corrupted cron jobs.

**Comment by akenion** [comment] 2024-01-30 16:24
Correct. Wordfence CLI and Wordfence plugin licenses are separate and non-interchangeable. They have different pricing models and allowed uses. Commercial CLI licenses are intended for use on multiple sites (within the respective tier limits) whereas paid plugin licenses are only intended for use on a single site.

**Comment by akenion** [comment] 2024-02-07 20:57
The encoding used by Python for IO streams can be controlled by the `PYTHONIOENCODING` environment variable. Setting this to `latin-1` allows recreating the error even on a terminal and shell configured to use `utf-8`.

**Comment by akenion** [comment] 2024-02-12 15:02
@davidnuzik noticed that the warning issued when using an encoding other than `utf-8` displays the `utf-8` in place of the original encoding.

**Comment by davidnuzik** [comment] 2024-02-12 16:27
v3.0.2rc3

**SUMMARY:**
QA validation PASSED.
I was effectively able to reproduce by actually setting LANG=en_US with v3.0.1 -- I got essentially the same issue but `UnicodeEncodeError: 'latin-1' codec can't encode characters in position 13-15: ordinal not in range(256)` which appears to essentially be the same thing. I tried `PYTHONIOENCODING=latin-1` but this didn't necessarily reproduce for me perhaps due to environmental differences. That said I believe I have successfully reproduced and validated the fix.

**REPRODUCTION STEPS**
1. On Ubuntu 22.04, specify my $LANG when invoking Wordfence CLI v3.0.1 like `LANG=en_US wordfence version --debug` this caused the aforementioned error, precisely the same error outlined in the issue.

**VALIDATION STEPS**
1. On the same environment, execute the reproduction step again, but with v3.0.2rc3. The CLI doesn't show the banner but it also doesn't crash. I see a warning: `Encoding for stdout is iso8859-1 instead of utf-8`. The CLI otherwise behaves normally.
2. Smoke test by doing the same but with the subcommands. No issues; only the banner doesn't show (expected) and the encoding warning is shown (expected) are different compared to a utf-8 shell.

**Closed** 2024-02-12 19:06 UTC
Labels: bug, dev-complete, qa-passed

**Comment by cwgrote** [comment] 2024-02-13 12:39
Running a "malware-scan" without "--no-banner" now produces an informational message "Encoding for stdout is iso8859-1 instead of utf-8" on my system (Ubuntu 22.04) with Wordfence-CLI updated to 3.02. No banner is displayed as expected. Thank you for your quick attention to this issue.
